version: 2
updates:
  - package-ecosystem: pip
    directory: "/api"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(api)"

  - package-ecosystem: pip
    directory: "/ui-pytest"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(ui-pytest)"

  - package-ecosystem: pip
    directory: "/backend"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(backend)"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
